name: CI Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
      # 1. Скачиваем код (этот шаг теперь работает отлично)
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # 2. Просто выводим тестовое сообщение
      - name: Say Hello
        run: echo "Привет! Экшен успешно запустился и выполнил этот шаг."

      # 3. Показываем версию операционной системы раннера
      - name: Check System Info
        run: |
          echo "Текущая дата и время на сервере:"
          date
          echo "Версия Ubuntu:"
          lsb_release -a
